version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-8528282}
      POSTGRES_DB: ${POSTGRES_DB:-job}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    command: postgres -N 1000
